name: 'PkgWatch Scan'
description: 'Scan npm and Python dependencies for health risks and security issues'
author: 'PkgWatch'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  api-key:
    description: 'PkgWatch API key. Get one at https://pkgwatch.dev'
    required: true
  working-directory:
    description: 'Directory containing package.json or requirements.txt to scan'
    required: false
    default: '.'
  scan-mode:
    description: 'Scan mode: single (default) scans one manifest, recursive scans all manifests in repo'
    required: false
    default: 'single'
  exclude-patterns:
    description: 'Glob patterns to exclude when using recursive mode (comma-separated)'
    required: false
    default: ''
  max-manifests:
    description: 'Maximum number of manifests to scan in recursive mode (default: 100)'
    required: false
    default: '100'
  fail-on:
    description: 'Fail workflow if risk level reached: HIGH or CRITICAL'
    required: false
    default: ''
  include-dev:
    description: 'Include devDependencies in scan'
    required: false
    default: 'true'
  soft-fail:
    description: 'Set outputs but do not fail the workflow even if risk threshold exceeded'
    required: false
    default: 'false'

outputs:
  total:
    description: 'Total packages scanned'
  critical:
    description: 'Count of CRITICAL risk packages'
  high:
    description: 'Count of HIGH risk packages'
  medium:
    description: 'Count of MEDIUM risk packages'
  low:
    description: 'Count of LOW risk packages'
  has-issues:
    description: 'True if any CRITICAL or HIGH risk packages found'
  highest-risk:
    description: 'Highest risk level found (CRITICAL, HIGH, MEDIUM, LOW, NONE)'
  failed:
    description: 'True if fail-on threshold was exceeded'
  results:
    description: 'Full scan results as JSON string'
  not-found-count:
    description: 'Count of packages not found in registry'
  manifests-scanned:
    description: 'Number of manifest files scanned (recursive mode only)'
  manifests-failed:
    description: 'Number of manifest files that failed to scan (recursive mode only)'
  per-manifest-results:
    description: 'JSON object with results per manifest file (recursive mode only)'
  truncated:
    description: 'True if max-manifests limit was reached (recursive mode only)'

runs:
  using: 'node20'
  main: 'dist/index.js'
